name: Run Lambda on Weekdays Midnight JST

on:
  schedule:
    - cron: "0 15 * * 1-5" # 月〜金のJST 0時
permissions:
  id-token: write # ← OIDCで必要
  contents: read # ← checkoutに必要

jobs:
  run_lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: ${{ secrets.HELLO_WORK_CRAWLER_INVOCATION_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --upgrade --user awscli
          export PATH=$PATH:~/.local/bin

      - name: Invoke Lambda function
        run: |
          aws lambda invoke \
            --function-name HeadlessCrawlerStack-JobNumberExtractorCrawlingFun-HDmF0aF3VF7U \
            --payload '{}' \
            response.json
